MBEx/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include("member.urls")),
    path('board/', include("board.urls")),
]

#localhost:8000/member/...
#localhost:8000/board/...

board/urls.py
'''
Created on 2022. 12. 6.

@author: joonj
'''
#urls.py
from django.urls.conf import path
from board import views

app_name="board"

urlpatterns=[
    path("list", views.ListView.as_view(), name="list"),
    path("bwrite", views.BWriteView.as_view(), name="bwrite"),
    path("detail", views.DetailView.as_view(), name="detail"),
    path("bdelete", views.BDeleteView.as_view(), name="bdelete"),
    
    ]

board/models.py
from django.db import models

# Create your models here.

class Board(models.Model):
    num = models.AutoField(verbose_name="글번호", primary_key=True)
    writer = models.CharField(verbose_name="작성자", null=False, max_length=50)
    subject = models.CharField(verbose_name="글제목", null=False, max_length=300)
    passwd = models.CharField(verbose_name="글비밀번호", null=False, max_length=30)
    content = models.TextField(verbose_name="글내용", null=False)
    readcount = models.IntegerField(verbose_name="조회수", default=0)
    ref = models.IntegerField(verbose_name="그룹화아이디")
    restep = models.IntegerField(verbose_name="글순서")
    relevel = models.IntegerField(verbose_name="글레벨")
    regdate = models.DateTimeField(verbose_name="작성일", auto_now_add=True, blank=True)
    ip = models.CharField(verbose_name="작성자ip", max_length=30)

board/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
import logging
from django.template import loader
from django.http.response import HttpResponse
from board.models import Board
from django.utils.dateformat import DateFormat
from datetime import datetime
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
logger = logging.getLogger(__name__)

class ListView(View):
    def get(self, request):
        template = loader.get_template("list.html")
        count = Board.objects.all().count()
        
        pagesize=10
        pageblock = 3
        
        pagenum = request.GET.get("pagenum")
        if not pagenum:
            pagenum = "1"
            
        pagenum = int(pagenum)
        start = (pagenum-1) * pagesize
        end = (start+pagesize)
        
        if end>count:
            end = count
            
        dtos = Board.objects.all().order_by("-ref", "restep")[start:end]
        number = count -(pagenum -1)*int(pagesize)
            
        pagecount = count // int(pagesize)
        if(count % int(pagesize)>0):
            pagecount += 1
        startpage = pagenum // int(pageblock) * int(pageblock) +1
        if (pagenum % int(pageblock) ==0) :
            startpage -= pageblock
            
        endpage = startpage + pageblock -1
        if endpage > pagecount : 
            endpage = pagecount
        pages = range(startpage, endpage+1)
            
        context = {
            "count" : count,
            "dtos":dtos,
            "number":number,
            "pagenum":pagenum,
            "pagecount" : pagecount,
            "startpage" : startpage,
            "endpage" : endpage,
            "pages" : pages, 
            "pageblock":pageblock,
            }
        
        return HttpResponse(template.render(context, request))
    
class BWriteView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return View.dispatch(self, request, *args, **kwargs)
    
    def get(self, request):
        template = loader.get_template("bwrite.html")
        
        #제목 글인 경우
        ref = 1
        restep = 0
        relevel = 0
        num = request.GET.get("num")
        
        if num==None:
            #제목 글인 경우
            try:
                #기존 글이 있는 경우
                maxnum = Board.objects.order_by("-num").values()[0]["num"]
                ref = maxnum +1   #그룹화 아이디 = 글번호 최댓값 +1
            except IndexError:
                #글이 없는 경우
                ref = 1
            
        else:
            #답글인 경우
            ref = request.GET.get("ref")
            restep = request.GET.get("restep")
            relevel = request.GET.get("relevel")
            
            res = Board.objects.filter(ref__exact=ref).filter(restep__gt=restep)
            for re in res:
                re.restep = re.restep+1
                re.save()
                
            restep = int(restep)+1
            relevel = int(relevel)+1
        
        context={
            "num" : num,
            "ref" : ref,
            "restep":restep,
            "relevel":relevel,
            }
        return HttpResponse(template.render(context, request))
    
    def post(self, request):
        dto = Board(
            writer = request.POST["writer"],
            subject = request.POST["subject"],
            content = request.POST["content"],
            passwd = request.POST["passwd"],
            readcount = 0,
            ref = request.POST["ref"],
            restep = request.POST["restep"],
            relevel=request.POST["relevel"],
            regdate = DateFormat(datetime.now()).format("Ymd"),
            ip = request.META.get("REMOTE_ADDR")
            )
        
        dto.save()
        return redirect("board:list")
    
class DetailView(View):
    def get(self, request):
        num = request.GET["num"]
        pagenum = request.GET["pagenum"]
        number=request.GET["number"]
        dto = Board.objects.get(num=num)
        
        if dto.ip!=request.META.get("REMOTE_ADDR"):
            dto.readcount = dto.readcount+1
            dto.save()
        
        template = loader.get_template("detail.html") 
        context={
            "dto" : dto,
            "num" : num,
            "pagenum" : pagenum,
            "number":number,
            }
        return HttpResponse(template.render(context, request))
    
    def post(self, request):
        pass
    
class BDeleteView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return View.dispatch(self, request, *args, **kwargs)
    
    def get(self, request):
        template = loader.get_template("bdelete.html")
        num = request.GET["num"]
        pagenum = request.GET["pagenum"]
        context = {
            "num" : num,
            "pagenum" : num,
            }
    
        return HttpResponse(template.render(context, request))
    
    def post(self, request):
        num = request.POST["num"]
        pagenum = request.POST["pagenum"]
        passwd = request.POST["passwd"]
        
        dto = Board.objects.get(num=num)
        if passwd == dto.passwd : 
            #비밀번호가 같다
            res = Board.objects.filter(ref__exact=dto.ref).filter(restep__exact=dto.restep+1).filter(relevel__gt=dto.relevel)
            if len(res)==0:
                #답글 없음
                logger.info("답글없음.")
            else:
                #답글 있음
                logger.info("답글있음.")
            return redirect("board:list") 
        else:
            #비밀번호가 다르다
            template = loader.get_template("bdelete.html")
            context={
                "num" : num,
                "pagenum" : pagenum,
                "message" : "비밀번호 다릅니다."
                }
            return HttpResponse(template.render(context, request))

board/templates/base_board.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>BASE</title>
		<link type="text/css" rel="stylesheet" href="{% static 'css/style_board.css' %}">
		<script src = "{% static 'js/jquery-3.6.1.js'%}"></script>
		<script src = "{% static 'js/script_board.js'%}"></script>
	</head>
	<body>
		{% block header %}
			<div id = "header">
				<a href="/member/main">회원 관리</a> &nbsp;
				<a href="/board/list">게시판</a>
			</div>
		{% endblock %}
		<br>
		{%block title%}
			<h2>게시판</h2>
		{%endblock%}
		
		{%block content%}
			게시글 내용 empty
		{%endblock%}
	</body>
</html>

board/templates/bdelete.html
{% extends "base_board.html" %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Insert title here</title>
	</head>
	<body>
		{% block title%}
			<h2>글 삭제</h2>
		{% endblock %}
		{% block content %}
			<form method="post" action="bdelete" name="passwdform" id="passwdform">
			{% csrf_token %}
			<input type="hidden" name="num" value="{{num}}" id="num">
			<input type="hidden" name="pagenum" value="{{pagenum}}" id="pagenum">
			<table>
				<tr>
					<th colspan="2">
						{% if message %}
							{{message}}
						{% else %}
							비밀번호를 다시 입력하세요
						{% endif %}
					</th>
				</tr>
				<tr>
					<th>비밀번호</th>
					<td><input class="input" type="password" name="passwd" id="passwd" maxlength="30" autofocus></td>
				</tr>
				<tr>
					<th colspan="2">
						<input class="inputbutton" type="submit" value="삭제">
						<input class="inputbutton" type="button" value="취소"
						onclick="location='list?pagenm={{passwo}}'">
					</th>
				</tr>
			</table>
			</form>
			
		{% endblock %}
	</body>
</html>

board/templates/bwrite.html
{% extends "base_board.html" %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Insert title here</title>
	</head>
	<body>
		{% block title%}
		{% endblock %}
		{% block content%}
		<form method="post" action="bwrite" name="inputform" id="inputform">
			{% csrf_token %}
			<input type="hidden" name="num" id="num" value="{{num}}">
			<input type="hidden" name="ref" id="ref" value="{{ref}}">
			<input type="hidden" name="restep" id="restep" value="{{restep}}">
			<input type="hidden" name="relevel" id="relevel" value="{{relevel}}">
			
			<table>
				<tr>
					<th colspan="2" style="text-align : right">
						<a href="list">글목록</a>&nbsp;
					</th>
				</tr>
				<tr>
					<th>작성자</th>
					<td>
						<input class="input" type="text" name="writer" id="writer" maxlength="50" autofocus>
					</td>
				</tr>
				<tr>
					<th>글제목</th>
					<td>
						<input class="input" type="text" name="subject" id="subject" maxlength="300">
					</td>
				</tr>
				<tr>
					<th>글내용</th>
					<td>
						<textarea rows="10" name="content" id="content"></textarea>
					</td>
				</tr>
				<tr>
					<th>비밀번호</th>
					<td>
						<input class="input" type="password" name="passwd" id="passwd" maxlength="30">
					</td>
				</tr>
				<tr>
					<th colspan="2">
						<input class="inputbutton" type="submit" value="작성">
						<input class="inputbutton" type="reset" value="취소">
						<input class="inputbutton" type="button" value="목록" onclick="location='list'">
					</th>
				</tr>
			</table>
		</form>
		{% endblock %}
	</body>
</html>

board/templates/detail.html
{% extends "base_board.html" %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Insert title here</title>
	</head>
	<body>
		{% block title %}
			<h2>글보기</h2>
		{% endblock %}
		
		{% block content %}
			<table>
				<tr>
					<th>글번호</th>
					<td style="text-align:center">{{number}}</td>
					<th>조회수</th>
					<td style="text-align:center">{{dto.readcount}}</td>
				</tr>
				<tr>
					<th>글제목</th>
					<td colspan="3">
						{{dto.subject}}
					</td>
				</tr>
				<tr>
					<th>글 내용</th>
					<td colspan="3">
						<pre>{{dto.content}}</pre>
					</td>
				</tr>
				<tr>
					<th colspan="4">
						<input class="inputbutton" type="button" value="수정" onclick="location='bmodify?num={{dto.num}}&pagenum={{pagenum}}'">
						<input class="inputbutton" type="button" value="삭제" onclick="location='bdelete?num={{dto.num}}&pagenum={{pagenum}}'">
						<input class="inputbutton" type="button" value="답글" onclick="location='bwrite?num={{dto.num}}&ref={{dto.ref}}&restep={{dto.restep}}&relevel={{dto.relevel}}'">
						<input class="inputbutton" type="button" value="목록" onclick="location='list?pagenum={{pagenum}}'">
					</th>
				</tr>
			</table>
		{% endblock %}
	</body>
</html>

board/templates/list.html
{% extends "base_board.html" %}
{% load mathfilters %}
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Insert title here</title>
	</head>
	<body>
		{% block title %}
		<h2>글 목록 (전체 글 : {{count}})</h2>
		{% endblock %}
		{% block content %}
			<table>
				<tr>
					<th colspan="6" style="text-align:right">
						<a href="{% url 'board:bwrite' %}">글쓰기</a> &nbsp;
						<!-- href = "bwrite" -->
					</th>
				</tr>
				<tr>
					<th style="width:8%">글번호</th>
					<th style="width:40%">글제목</th>
					<th style="width:15%">작성자</th>
					<th style="width:8%">조회수</th>
					<th style="width:15%">작성일</th>
					<th style="width:15%">IP</th>
				</tr>
				{% if count == 0 %}
				<tr>
					<td colspan="6" style="text-align:center">
						게시판에 글이 존재하지 않습니다.
						글쓰기를 눌러주세요.
					</td>
				</tr>
				{% else %}
					{% for dto in dtos %}
					<tr> 
					<!-- page_max_size // page 계산  num, number(50,49...), rownum(DB)   -->
					<!-- 바구니화 해서 구성. 보던 페이지로 다시 돌아 갈 수 있게끔 -->
						<td style="text-align:center">{{number|sub:forloop.counter0}}</td>
						<td>
							{% if dto.relevel > 1 %}
								<img src="{% static 'images/level.gif' %}" border="0" width="{{dto.relevel|mul:5}}" height="15">
							{% endif %}
							{% if dto.relevel > 0 %}
								<img src="{% static 'images/re.gif' %}" border="0" width="20" height="15">
							{% endif %}
							<a href="detail?num={{dto.num}}&pagenum={{pagenum}}&number={{number|sub:forloop.counter0}}">
							{{dto.subject}}
							</a>
						</td>
						<td style="text-align:center">{{dto.writer}}</td>
						<td style="text-align:center">{{dto.readcount}}</td>
						<td style="text-align:center">{{dto.regdate|date:'Y-m-d H:i'}}</td>
						<td>{{dto.ip}}</td>
					</tr>
					{% endfor %}
				{% endif %}
			</table>
			<br>
			{% if startpage > pageblock %}
				<a href="list">[◀◀]</a>
				<a href="list?pagenum={{startpage|sub:pageblock}}">[◀]</a>
			{% endif %}
			
			{% for i in pages %}
				{% if i == pagenum %}
					<span>[{{i}}]</span>
				{% else %}
					<a href="list?pagenum={{i}}">[{{i}}]</a>
				{% endif %}
			{% endfor %}
			
			{% if pagecount > endpage %}
				<a href="list?pagenum={{startpage|add:pageblock}}">[▶]</a>
				<a href="list?pagenum={{pagecount}}">[▶▶]</a>
			{% endif %}
		{% endblock %}
	</body>
</html>